### ISSUE TITLE
 convert from sqlitedb to mbtiles ?

### ISSUE THREAD

**Issue by Kobrairaq** [tarwirdur/mbtiles2osmand#5]
im trying to convert back from sqlitedb to mbtiles can u help please ?

**Comment by tarwirdur** [comment]
check this script: https://github.com/tarwirdur/mbtiles2osmand/blob/d1aae40a40aab36f46e95d249147ce68f0ccde76/osmand2mbtiles.py

I've tried to get mbtiles file, convert it into osmand format and back. Looks working.

**Comment by Kobrairaq** [comment]
> check this script: https://github.com/tarwirdur/mbtiles2osmand/blob/d1aae40a40aab36f46e95d249147ce68f0ccde76/osmand2mbtiles.py
> 
> 
> 
> I've tried to get mbtiles file, convert it into osmand format and back. Looks working.

I'll give it a shot today thank you very much .

**Comment by Kobrairaq** [comment]
> check this script: https://github.com/tarwirdur/mbtiles2osmand/blob/d1aae40a40aab36f46e95d249147ce68f0ccde76/osmand2mbtiles.py
> 
> 
> 
> I've tried to get mbtiles file, convert it into osmand format and back. Looks working.

It's working like a pie thank you you are the best .
